// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../alerts";
import { rpc, serverOnly } from "../../data/rpc";
export const createReminder = rpc("alerts.createReminder", core.createReminder);
export const deleteReminder = rpc("alerts.deleteReminder", core.deleteReminder);
export const markNotificationsRead = rpc("alerts.markNotificationsRead", core.markNotificationsRead);
export const updateReminder = rpc("alerts.updateReminder", core.updateReminder);
export { EMAIL_MIN_OFFSET, OFFSETS, fireReminders, nairobiInstant, nextFireAt, notificationsFor, pruneNotifications, remindersOn, targetWhen, unreadCount } from "../alerts";
export type { FireResult, ReminderInput, TargetWhen } from "../alerts";
