// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../callsheets";
import { rpc, serverOnly } from "../../data/rpc";
export const addRunItem = rpc("callsheets.addRunItem", core.addRunItem);
export const createCallSheet = rpc("callsheets.createCallSheet", core.createCallSheet);
export const deleteCallSheet = rpc("callsheets.deleteCallSheet", core.deleteCallSheet);
export const duplicateCallSheet = rpc("callsheets.duplicateCallSheet", core.duplicateCallSheet);
export const finalizeCallSheet = rpc("callsheets.finalizeCallSheet", core.finalizeCallSheet);
export const openOrCreateForRecord = rpc("callsheets.openOrCreateForRecord", core.openOrCreateForRecord);
export const removeRunItem = rpc("callsheets.removeRunItem", core.removeRunItem);
export const reopenCallSheet = rpc("callsheets.reopenCallSheet", core.reopenCallSheet);
export const resolveMismatches = rpc("callsheets.resolveMismatches", core.resolveMismatches);
export const updateCallSheet = rpc("callsheets.updateCallSheet", core.updateCallSheet);
export const updateRunItem = rpc("callsheets.updateRunItem", core.updateRunItem);
export { callSheetForRecord, crewConflicts, daysOf, duplicateOf, episodesOnDate, getCallSheet, getMismatches, runOfShowRequired, runOfShowTotals, sheetLevel, sortedRunOfShow } from "../callsheets";
export type { CallSheetInput, Mismatch, RunItemInput } from "../callsheets";
