// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../checks";
import { rpc, serverOnly } from "../../data/rpc";
export const dismissCheck = rpc("checks.dismissCheck", core.dismissCheck);
export const restoreCheck = rpc("checks.restoreCheck", core.restoreCheck);
export const setCheck = rpc("checks.setCheck", core.setCheck);
export { acceptsAtDevelopment, callSheetChecks, checksSummary, episodeChecks, projectChecks, recordingLogChecks, sessionChecks } from "../checks";
export type { CheckGroup, CheckItem, Checks } from "../checks";
