// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../docs";
import { rpc, serverOnly } from "../../data/rpc";
export const archiveDoc = rpc("docs.archiveDoc", core.archiveDoc);
export const archiveDocsFor = rpc("docs.archiveDocsFor", core.archiveDocsFor);
export const attachDoc = rpc("docs.attachDoc", core.attachDoc);
export const attachStageDocs = rpc("docs.attachStageDocs", core.attachStageDocs);
export const canEditDoc = rpc("docs.canEditDoc", core.canEditDoc);
export const canViewDoc = rpc("docs.canViewDoc", core.canViewDoc);
export const createDoc = rpc("docs.createDoc", core.createDoc);
export const docsForRecord = rpc("docs.docsForRecord", core.docsForRecord);
export const listDocs = rpc("docs.listDocs", core.listDocs);
export const restoreRevision = rpc("docs.restoreRevision", core.restoreRevision);
export const saveDoc = rpc("docs.saveDoc", core.saveDoc);
export { diffLines, docSubject, getDoc, revisionsOf } from "../docs";
export type { DiffLine, NewDocInput } from "../docs";
