// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../kits";
import { rpc, serverOnly } from "../../data/rpc";
export const createKit = rpc("kits.createKit", core.createKit);
export const deleteKit = rpc("kits.deleteKit", core.deleteKit);
export const updateKit = rpc("kits.updateKit", core.updateKit);
export { getKit, kitSuggestions, kitsForRole, listKits } from "../kits";
export type { KitInput, KitSuggestion } from "../kits";
