// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../lending";
import { rpc, serverOnly } from "../../data/rpc";
export const cancelLoan = rpc("lending.cancelLoan", core.cancelLoan);
export const createLoan = rpc("lending.createLoan", core.createLoan);
export const returnLoanItems = rpc("lending.returnLoanItems", core.returnLoanItems);
export const updateLoan = rpc("lending.updateLoan", core.updateLoan);
export { LOAN_EDITABLE, daysLate, getLoan, loanEnd, loansOut, outstanding, overdueLoans } from "../lending";
export type { LoanInput, LoanPatch, LoanReturnInput } from "../lending";
