// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../live";
import { rpc, serverOnly } from "../../data/rpc";
export const advanceRundown = rpc("live.advanceRundown", core.advanceRundown);
export const copyRundownToDays = rpc("live.copyRundownToDays", core.copyRundownToDays);
export const copyTechCheckFromPrevious = rpc("live.copyTechCheckFromPrevious", core.copyTechCheckFromPrevious);
export const setLiveLight = rpc("live.setLiveLight", core.setLiveLight);
export const setRundown = rpc("live.setRundown", core.setRundown);
export { gearNotReturned, liveNow, previousTechSheet, projectGearNotReturned, rundownOf, techCounts, techIssues } from "../live";
export type { NotReturned } from "../live";
