// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../locations";
import { rpc, serverOnly } from "../../data/rpc";
export const archiveLocation = rpc("locations.archiveLocation", core.archiveLocation);
export const canKeepLocations = rpc("locations.canKeepLocations", core.canKeepLocations);
export const createLocation = rpc("locations.createLocation", core.createLocation);
export const updateLocation = rpc("locations.updateLocation", core.updateLocation);
export { getLocation, listLocations, sheetsUsing } from "../locations";
export type { LocationInput } from "../locations";
