// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../people";
import { rpc, serverOnly } from "../../data/rpc";
export const assignToProject = rpc("people.assignToProject", core.assignToProject);
export const createPerson = rpc("people.createPerson", core.createPerson);
export const deactivatePerson = rpc("people.deactivatePerson", core.deactivatePerson);
export const reactivatePerson = rpc("people.reactivatePerson", core.reactivatePerson);
export const removeFromProject = rpc("people.removeFromProject", core.removeFromProject);
export const updateOwnProfile = rpc("people.updateOwnProfile", core.updateOwnProfile);
export const updatePerson = rpc("people.updatePerson", core.updatePerson);
export const updatePersonCategory = rpc("people.updatePersonCategory", core.updatePersonCategory);
export const createLoginForPerson = serverOnly("people.createLoginForPerson", core.createLoginForPerson);
export { crewAvailableOn, generatePersonId, getPerson, nameOf, projectHistory, workOwnedOn } from "../people";
export type { PersonInput } from "../people";
