// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../permissions";
import { rpc, serverOnly } from "../../data/rpc";
export const can = rpc("permissions.can", core.can);
export const modulesFor = rpc("permissions.modulesFor", core.modulesFor);
export const requireCan = rpc("permissions.requireCan", core.requireCan);
export const resetPermissions = rpc("permissions.resetPermissions", core.resetPermissions);
export const setPersonGrant = rpc("permissions.setPersonGrant", core.setPersonGrant);
export const setRoleGrant = rpc("permissions.setRoleGrant", core.setRoleGrant);
export { MODULE_LABELS, customisations, effectiveGrants, grantFor } from "../permissions";
export type { GrantSource, PermissionSettings } from "../permissions";
