// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../production";
import { rpc, serverOnly } from "../../data/rpc";
export const addEventDay = rpc("production.addEventDay", core.addEventDay);
export const applyDayToFuture = rpc("production.applyDayToFuture", core.applyDayToFuture);
export const canPlanEvent = rpc("production.canPlanEvent", core.canPlanEvent);
export const cancelDay = rpc("production.cancelDay", core.cancelDay);
export const createProduction = rpc("production.createProduction", core.createProduction);
export const resetToTemplate = rpc("production.resetToTemplate", core.resetToTemplate);
export const setDayLabel = rpc("production.setDayLabel", core.setDayLabel);
export const setShowSchedule = rpc("production.setShowSchedule", core.setShowSchedule);
export const setUpEventDays = rpc("production.setUpEventDays", core.setUpEventDays);
export const topUpShow = rpc("production.topUpShow", core.topUpShow);
export const updateEventPlan = rpc("production.updateEventPlan", core.updateEventPlan);
export const updateShowTemplate = rpc("production.updateShowTemplate", core.updateShowTemplate);
export { BOARD_AHEAD_DAYS, BOARD_PAST_DAYS, DAY_LABELS, DEFAULT_HORIZON_COUNT, DEFAULT_HORIZON_WEEKS, GEAR_WINDOW_DAYS, MAX_HORIZON_COUNT, MAX_HORIZON_WEEKS, checkEventSetup, dayTitle, daysOfEvent, followsTemplate, getTemplate, horizonEnd, instanceTitle, isLiveEvent, modeLabel, offSchedule, onBoard, productionOf, recurringDue, sheetOfDay, templateOfEvent, topUpRecurring } from "../production";
export type { EventSetup, ProductionInput, ScheduleResult, TemplatePatch, TemplateResult } from "../production";
