// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../production";
import { rpc, serverOnly } from "../../data/rpc";
export const addEventDay = rpc("production.addEventDay", core.addEventDay);
export const canPlanShow = rpc("production.canPlanShow", core.canPlanShow);
export const createProduction = rpc("production.createProduction", core.createProduction);
export const resetToTemplate = rpc("production.resetToTemplate", core.resetToTemplate);
export const setShowSchedule = rpc("production.setShowSchedule", core.setShowSchedule);
export const topUpShow = rpc("production.topUpShow", core.topUpShow);
export const updateEventPlan = rpc("production.updateEventPlan", core.updateEventPlan);
export const updateShowTemplate = rpc("production.updateShowTemplate", core.updateShowTemplate);
export { BOARD_AHEAD_DAYS, BOARD_PAST_DAYS, DEFAULT_HORIZON_WEEKS, GEAR_WINDOW_DAYS, MAX_HORIZON_WEEKS, daysOfShow, followsTemplate, getTemplate, instanceTitle, isShow, modeLabel, offSchedule, onBoard, productionOf, recurringDue, sheetOfDay, templateOfShow, topUpRecurring } from "../production";
export type { ProductionInput, ScheduleResult, TemplatePatch, TemplateResult } from "../production";
