// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../reminders";
import { rpc, serverOnly } from "../../data/rpc";
export const logSent = rpc("reminders.logSent", core.logSent);
export { alreadySent, dueSoon, lastSent, mailtoLink, messageFor, remindersFor, smsLink } from "../reminders";
export type { Message, Reminder } from "../reminders";
