// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../settings";
import { rpc, serverOnly } from "../../data/rpc";
export const updateSettings = rpc("settings.updateSettings", core.updateSettings);
export const changePassword = serverOnly("settings.changePassword", core.changePassword);
