// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../settings";
import { rpc, serverOnly } from "../../data/rpc";
export const setFeature = rpc("settings.setFeature", core.setFeature);
export const updateSettings = rpc("settings.updateSettings", core.updateSettings);
export const updateWorkspaceAppearance = rpc("settings.updateWorkspaceAppearance", core.updateWorkspaceAppearance);
export const changePassword = serverOnly("settings.changePassword", core.changePassword);
export { SETTINGS_EDITABLE, featureOn } from "../settings";
