// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../storage";
import { rpc, serverOnly } from "../../data/rpc";
export const addAllocation = rpc("storage.addAllocation", core.addAllocation);
export const clearRecordFromDrives = rpc("storage.clearRecordFromDrives", core.clearRecordFromDrives);
export const createDrive = rpc("storage.createDrive", core.createDrive);
export const deleteDrive = rpc("storage.deleteDrive", core.deleteDrive);
export const hasStorageAccess = rpc("storage.hasStorageAccess", core.hasStorageAccess);
export const removeAllocation = rpc("storage.removeAllocation", core.removeAllocation);
export const updateAllocation = rpc("storage.updateAllocation", core.updateAllocation);
export const updateDrive = rpc("storage.updateDrive", core.updateDrive);
export { allDriveUsage, allocationsForRecord, driveReportText, driveUsage, fleetReportText, fleetTotals, forecast, getDrive, isNearlyFull, recordSnapshot } from "../storage";
export type { AllocationInput, DriveInput, DriveUsage, Forecast } from "../storage";
