// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.
import * as core from "../team";
import { rpc, serverOnly } from "../../data/rpc";
export const addTeamMember = rpc("team.addTeamMember", core.addTeamMember);
export const setMemberRoles = rpc("team.setMemberRoles", core.setMemberRoles);
export { cleanRoles, knownRoles, nameWithRole, roleOn, rolesOf, rolesOnProject, teamOf } from "../team";
export type { TeamEntry } from "../team";
