// Bundles the server code (server/ and the rules in src/) into one file that Vercel runs: api/_server.mjs.
// Run it after changing anything under server/ or src/services/, and commit the result:  npm run build:server
import { build } from "esbuild";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
await build({
  entryPoints: [resolve(root, "server/index.ts")],
  outfile: resolve(root, "api/_server.mjs"),
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  packages: "external",
  logLevel: "info",
  banner: { js: "// GENERATED by scripts/build-server.mjs from /server and /src. Do not edit. Run `npm run build:server` after changing them." },
});
