// Writes src/services/wrapped/*.ts: the same functions as the service files, but recorded when they
// change data (see src/data/rpc.ts). Run it after adding or renaming a service function:  npm run gen
// Pass --out <dir> to write elsewhere (used by `npm run gen:check` to generate into a temp directory
// and diff against what is committed, without touching the real files).
import ts from "typescript";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const outFlagIdx = process.argv.indexOf("--out");
const outDir = outFlagIdx !== -1 && process.argv[outFlagIdx + 1] ? resolve(process.argv[outFlagIdx + 1]) : resolve(root, "src/services/wrapped");
const MODULES = ["callsheets", "content", "docs", "equipment", "people", "permissions", "reminders", "settings", "storage", "team"];
// Anything that touches passwords or logins is done by the server's account endpoints, never replayed.
const SERVER_ONLY = new Set(["people.createLoginForPerson", "settings.changePassword"]);

const files = MODULES.map((m) => resolve(root, `src/services/${m}.ts`));
const options = { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.ESNext, moduleResolution: ts.ModuleResolutionKind.Bundler, jsx: ts.JsxEmit.ReactJSX, skipLibCheck: true, strict: true, allowImportingTsExtensions: true, noEmit: true };
const program = ts.createProgram(files, options);
const checker = program.getTypeChecker();

const names = {};
mkdirSync(outDir, { recursive: true });

for (const m of MODULES) {
  const sf = program.getSourceFile(resolve(root, `src/services/${m}.ts`));
  const mod = checker.getSymbolAtLocation(sf);
  const types = [], plain = [], wrapped = [], blocked = [];
  for (const sym of checker.getExportsOfModule(mod)) {
    const name = sym.getName();
    const target = sym.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(sym) : sym;
    const isValue = (target.flags & ts.SymbolFlags.Value) !== 0;
    if (!isValue) { types.push(name); continue; }
    const decl = target.valueDeclaration ?? target.declarations?.[0];
    const type = checker.getTypeOfSymbolAtLocation(target, decl);
    const sigs = type.getCallSignatures();
    if (sigs.length === 0 || (target.flags & ts.SymbolFlags.Class)) { plain.push(name); continue; }
    const first = sigs[0].getParameters()[0]?.getName();
    if (SERVER_ONLY.has(`${m}.${name}`)) blocked.push(name);
    else if (first === "actor") wrapped.push(name);
    else {
      plain.push(name);
      // A function that changes data but does not take an actor first could not be replayed by the server.
      if (decl && /\bcommit\(\)/.test(decl.getText())) console.warn(`WARNING: ${m}.${name} changes data but does not take an actor first`);
    }
  }
  names[m] = wrapped.sort();
  const out = [
    "// GENERATED by scripts/gen-wrapped.mjs. Do not edit. Run `npm run gen` after changing a service.",
    `import * as core from "../${m}";`,
    `import { rpc, serverOnly } from "../../data/rpc";`,
    ...wrapped.sort().map((n) => `export const ${n} = rpc("${m}.${n}", core.${n});`),
    ...blocked.sort().map((n) => `export const ${n} = serverOnly("${m}.${n}", core.${n});`),
    plain.length ? `export { ${plain.sort().join(", ")} } from "../${m}";` : "",
    types.length ? `export type { ${types.sort().join(", ")} } from "../${m}";` : "",
    "",
  ].filter((l) => l !== "").join("\n") + "\n";
  writeFileSync(resolve(outDir, `${m}.ts`), out);
}
writeFileSync(resolve(outDir, "names.ts"), `// GENERATED by scripts/gen-wrapped.mjs. The service functions the server will run for a signed-in person.\nexport const RPC_NAMES: Record<string, string[]> = ${JSON.stringify(names, null, 2)};\n`);
console.log(Object.entries(names).map(([m, n]) => `${m}: ${n.length}`).join(", "));
